"""HTML report generator for RSS content - Modern Dark Theme Version."""

from datetime import datetime
from typing import List, Dict
import html


class HTMLReportGenerator:
    """Generate HTML reports from RSS feeds."""

    def __init__(self, title: str = "RSS Report"):
        self.title = title

    def generate(self, items: List[Dict], theme: str = "default") -> str:
        """Generate HTML report from items."""
        css = self._get_css(theme)

        html_content = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(self.title)}</title>
    <style>{css}</style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{html.escape(self.title)}</h1>
            <p class="meta">Generated at {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
        </header>
        <main>
            {self._generate_items_html(items)}
        </main>
        <footer>
            <p>Generated by RSS Manager</p>
        </footer>
    </div>
</body>
</html>"""
        return html_content

    def generate_github_trending_html(
        self,
        title: str,
        subtitle: str,
        items: List[Dict],
        theme: str = "dark"
    ) -> str:
        """
        Generate a modern dark-themed HTML report for GitHub trending repositories.

        Args:
            title: Main title of the report
            subtitle: Subtitle/description
            items: List of repository dictionaries with keys:
                - rank: int
                - name: str (repository name)
                - owner: str (owner username)
                - stars: int (total stars)
                - stars_growth: int (stars gained)
                - description: str
                - topics: List[str]
                - url: str
            theme: Color theme (default: "dark")

        Returns:
            Complete HTML document as string
        """
        css = self._get_github_css()

        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(title)}</title>
    <style>{css}</style>
</head>
<body>
    <div class="container">
        <header class="report-header">
            <div class="header-content">
                <h1>{html.escape(title)}</h1>
                <p class="subtitle">{html.escape(subtitle)}</p>
                <p class="meta">Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}</p>
            </div>
        </header>
        <main>
            {self._generate_github_cards(items)}
        </main>
        <footer class="report-footer">
            <p>Generated by RSS Manager</p>
        </footer>
    </div>
</body>
</html>"""
        return html_content

    def _get_css(self, theme: str) -> str:
        """Get CSS styles for the report."""
        return """
            * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }

            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                padding: 20px;
            }

            .container {
                max-width: 1200px;
                margin: 0 auto;
            }

            header {
                text-align: center;
                padding: 40px 0;
                color: white;
            }

            header h1 {
                font-size: 2.5em;
                margin-bottom: 10px;
                text-shadow: 2px 2px 4px rgba(0,0,0,0.2);
            }

            .meta {
                font-size: 1.1em;
                opacity: 0.9;
            }

            main {
                background: white;
                border-radius: 20px;
                padding: 40px;
                box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            }

            .category {
                margin-bottom: 40px;
            }

            .category-title {
                font-size: 1.8em;
                color: #333;
                border-bottom: 3px solid #667eea;
                padding-bottom: 10px;
                margin-bottom: 20px;
            }

            .item {
                background: #f8f9fa;
                border-radius: 12px;
                padding: 20px;
                margin-bottom: 15px;
                transition: all 0.3s ease;
                border-left: 4px solid #667eea;
            }

            .item:hover {
                transform: translateX(5px);
                box-shadow: 0 5px 20px rgba(102, 126, 234, 0.2);
            }

            .item-header {
                display: flex;
                align-items: center;
                margin-bottom: 10px;
            }

            .item-number {
                background: #667eea;
                color: white;
                width: 30px;
                height: 30px;
                border-radius: 50%;
                display: flex;
                align-items: center;
                justify-content: center;
                font-weight: bold;
                margin-right: 15px;
            }

            .item-title {
                font-size: 1.3em;
                color: #333;
                text-decoration: none;
                font-weight: 600;
                flex: 1;
            }

            .item-title:hover {
                color: #667eea;
            }

            .item-source {
                display: inline-block;
                background: #e3f2fd;
                color: #1976d2;
                padding: 4px 12px;
                border-radius: 20px;
                font-size: 0.85em;
                margin-left: 10px;
            }

            .item-meta {
                color: #666;
                font-size: 0.9em;
                margin-top: 8px;
            }

            .item-summary {
                color: #555;
                line-height: 1.6;
                margin-top: 10px;
                padding-left: 45px;
            }

            .stats {
                display: flex;
                gap: 20px;
                margin-top: 10px;
                padding-left: 45px;
            }

            .stat {
                display: flex;
                align-items: center;
                color: #888;
                font-size: 0.85em;
            }

            .stat-icon {
                margin-right: 5px;
            }

            footer {
                text-align: center;
                padding: 30px;
                color: white;
                opacity: 0.8;
            }

            @media (max-width: 768px) {
                header h1 {
                    font-size: 1.8em;
                }

                main {
                    padding: 20px;
                }

                .item-title {
                    font-size: 1.1em;
                }
            }
        """

    def _get_github_css(self) -> str:
        """Get modern dark theme CSS for GitHub trending reports."""
        return """
            :root {
                --bg-primary: #0d1117;
                --bg-secondary: #161b22;
                --bg-card: #1c2128;
                --bg-card-hover: #22262e;
                --border-color: #30363d;
                --border-hover: #8b949e;
                --text-primary: #c9d1d9;
                --text-secondary: #8b949e;
                --text-muted: #6e7681;
                --accent-gold: #e3b341;
                --accent-silver: #a5b4fc;
                --accent-bronze: #d97757;
                --accent-blue: #58a6ff;
                --accent-green: #3fb950;
                --accent-purple: #a371f7;
                --star-color: #e3b341;
                --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.3);
                --shadow-md: 0 4px 6px rgba(0, 0, 0, 0.4);
                --shadow-lg: 0 10px 30px rgba(0, 0, 0, 0.5);
                --radius-sm: 6px;
                --radius-md: 8px;
                --radius-lg: 12px;
            }

            * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }

            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
                background-color: var(--bg-primary);
                background-image: radial-gradient(ellipse 80% 50% at 50% -20%, rgba(88, 166, 255, 0.08), transparent),
                                  radial-gradient(ellipse 60% 40% at 80% 100%, rgba(163, 113, 247, 0.05), transparent);
                color: var(--text-primary);
                min-height: 100vh;
                line-height: 1.6;
                -webkit-font-smoothing: antialiased;
                -moz-osx-font-smoothing: grayscale;
            }

            .container {
                max-width: 1280px;
                margin: 0 auto;
                padding: 40px 24px;
            }

            /* Header Styles */
            .report-header {
                text-align: center;
                padding: 60px 0 48px;
                border-bottom: 1px solid var(--border-color);
                margin-bottom: 48px;
            }

            .header-content h1 {
                font-size: clamp(2rem, 5vw, 3rem);
                font-weight: 800;
                letter-spacing: -0.025em;
                margin-bottom: 16px;
                background: linear-gradient(135deg, #ffffff 0%, #c9d1d9 100%);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
            }

            .subtitle {
                font-size: 1.125rem;
                color: var(--text-secondary);
                max-width: 600px;
                margin: 0 auto 12px;
                line-height: 1.6;
            }

            .meta {
                font-size: 0.875rem;
                color: var(--text-muted);
                font-variant-numeric: tabular-nums;
            }

            /* Grid Layout */
            .cards-grid {
                display: grid;
                grid-template-columns: repeat(2, 1fr);
                gap: 20px;
                margin-bottom: 48px;
            }

            /* Card Styles */
            .repo-card {
                background: var(--bg-card);
                border: 1px solid var(--border-color);
                border-radius: var(--radius-lg);
                padding: 24px;
                transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
                position: relative;
                overflow: hidden;
            }

            .repo-card::before {
                content: '';
                position: absolute;
                top: 0;
                left: 0;
                right: 0;
                height: 1px;
                background: linear-gradient(90deg, transparent, rgba(88, 166, 255, 0.3), transparent);
                opacity: 0;
                transition: opacity 0.25s ease;
            }

            .repo-card:hover {
                background: var(--bg-card-hover);
                border-color: var(--border-hover);
                transform: translateY(-2px);
                box-shadow: var(--shadow-lg);
            }

            .repo-card:hover::before {
                opacity: 1;
            }

            /* Card Header */
            .card-header {
                display: flex;
                align-items: flex-start;
                gap: 16px;
                margin-bottom: 16px;
            }

            .rank-badge {
                width: 36px;
                height: 36px;
                border-radius: 50%;
                display: flex;
                align-items: center;
                justify-content: center;
                font-weight: 700;
                font-size: 0.875rem;
                flex-shrink: 0;
                font-variant-numeric: tabular-nums;
                background: var(--bg-secondary);
                border: 2px solid var(--border-color);
                color: var(--text-secondary);
                transition: all 0.2s ease;
            }

            .repo-card:hover .rank-badge {
                transform: scale(1.1);
            }

            .rank-1 {
                background: linear-gradient(135deg, rgba(227, 179, 65, 0.15) 0%, rgba(227, 179, 65, 0.05) 100%);
                border-color: var(--accent-gold);
                color: var(--accent-gold);
                box-shadow: 0 0 20px rgba(227, 179, 65, 0.2);
            }

            .rank-2 {
                background: linear-gradient(135deg, rgba(165, 180, 252, 0.15) 0%, rgba(165, 180, 252, 0.05) 100%);
                border-color: var(--accent-silver);
                color: var(--accent-silver);
                box-shadow: 0 0 20px rgba(165, 180, 252, 0.15);
            }

            .rank-3 {
                background: linear-gradient(135deg, rgba(217, 119, 87, 0.15) 0%, rgba(217, 119, 87, 0.05) 100%);
                border-color: var(--accent-bronze);
                color: var(--accent-bronze);
                box-shadow: 0 0 20px rgba(217, 119, 87, 0.15);
            }

            /* Repo Info */
            .repo-info {
                flex: 1;
                min-width: 0;
            }

            .repo-name {
                font-size: 1.125rem;
                font-weight: 600;
                color: var(--accent-blue);
                text-decoration: none;
                display: block;
                margin-bottom: 4px;
                white-space: nowrap;
                overflow: hidden;
                text-overflow: ellipsis;
                transition: color 0.2s ease;
            }

            .repo-name:hover {
                color: #79b8ff;
                text-decoration: underline;
            }

            .repo-owner {
                font-size: 0.875rem;
                color: var(--text-muted);
                font-weight: 400;
            }

            /* Stars Section */
            .stars-section {
                display: flex;
                align-items: center;
                gap: 12px;
                margin-bottom: 16px;
                padding: 12px 16px;
                background: var(--bg-secondary);
                border-radius: var(--radius-md);
                border: 1px solid var(--border-color);
            }

            .stars-total {
                display: flex;
                align-items: center;
                gap: 6px;
                font-weight: 700;
                font-size: 1.125rem;
                color: var(--text-primary);
            }

            .star-icon {
                color: var(--star-color);
                font-size: 1rem;
            }

            .stars-growth {
                display: flex;
                align-items: center;
                gap: 4px;
                font-size: 0.875rem;
                font-weight: 600;
                color: var(--accent-green);
                background: rgba(63, 185, 80, 0.1);
                padding: 4px 10px;
                border-radius: var(--radius-sm);
            }

            .growth-icon {
                font-size: 0.75rem;
            }

            /* Description */
            .repo-description {
                font-size: 0.9375rem;
                color: var(--text-secondary);
                line-height: 1.6;
                margin-bottom: 16px;
                display: -webkit-box;
                -webkit-line-clamp: 3;
                -webkit-box-orient: vertical;
                overflow: hidden;
            }

            /* Topics */
            .repo-topics {
                display: flex;
                flex-wrap: wrap;
                gap: 8px;
            }

            .topic-tag {
                display: inline-flex;
                align-items: center;
                padding: 4px 10px;
                background: rgba(88, 166, 255, 0.1);
                border: 1px solid rgba(88, 166, 255, 0.2);
                border-radius: var(--radius-sm);
                font-size: 0.75rem;
                font-weight: 500;
                color: var(--accent-blue);
                text-decoration: none;
                transition: all 0.15s ease;
            }

            .topic-tag:hover {
                background: rgba(88, 166, 255, 0.2);
                border-color: rgba(88, 166, 255, 0.4);
                transform: translateY(-1px);
            }

            /* Footer */
            .report-footer {
                text-align: center;
                padding: 48px 0;
                border-top: 1px solid var(--border-color);
                color: var(--text-muted);
                font-size: 0.875rem;
            }

            /* Empty State */
            .empty-state {
                text-align: center;
                padding: 80px 40px;
                color: var(--text-muted);
            }

            .empty-state-icon {
                font-size: 3rem;
                margin-bottom: 16px;
                opacity: 0.5;
            }

            /* Responsive Design */
            @media (max-width: 968px) {
                .cards-grid {
                    grid-template-columns: 1fr;
                    gap: 16px;
                }

                .container {
                    padding: 24px 16px;
                }

                .report-header {
                    padding: 40px 0 32px;
                    margin-bottom: 32px;
                }

                .repo-card {
                    padding: 20px;
                }
            }

            @media (max-width: 640px) {
                .header-content h1 {
                    font-size: 1.75rem;
                }

                .subtitle {
                    font-size: 1rem;
                }

                .stars-section {
                    flex-wrap: wrap;
                    gap: 8px;
                }

                .card-header {
                    gap: 12px;
                }

                .rank-badge {
                    width: 32px;
                    height: 32px;
                    font-size: 0.8rem;
                }

                .repo-name {
                    font-size: 1rem;
                }
            }

            /* Print Styles */
            @media print {
                body {
                    background: white;
                    color: black;
                }

                .repo-card {
                    break-inside: avoid;
                    border: 1px solid #ddd;
                }
            }

            /* Reduced Motion */
            @media (prefers-reduced-motion: reduce) {
                .repo-card,
                .rank-badge,
                .topic-tag {
                    transition: none;
                }
            }

            /* Selection */
            ::selection {
                background: rgba(88, 166, 255, 0.3);
                color: var(--text-primary);
            }
        """

    def _generate_items_html(self, items: List[Dict]) -> str:
        """Generate HTML for items grouped by category."""
        if not items:
            return '<p class="no-items">No items found.</p>'

        # Group items by category
        categories = {}
        for item in items:
            cat = item.get('category', 'Uncategorized')
            if cat not in categories:
                categories[cat] = []
            categories[cat].append(item)

        html_parts = []
        for category, cat_items in categories.items():
            html_parts.append(self._generate_category_html(category, cat_items))

        return '\n'.join(html_parts)

    def _generate_category_html(self, category: str, items: List[Dict]) -> str:
        """Generate HTML for a category."""
        items_html = []
        for i, item in enumerate(items, 1):
            title = html.escape(item.get('title', 'No title'))
            url = html.escape(item.get('url', ''))
            source = html.escape(item.get('source', 'Unknown'))
            summary = html.escape(item.get('summary', ''))
            date = html.escape(item.get('published', ''))

            summary_html = f'<p class="item-summary">{summary}</p>' if summary else ''

            item_html = f"""
            <div class="item">
                <div class="item-header">
                    <span class="item-number">{i}</span>
                    <a href="{url}" target="_blank" class="item-title">{title}</a>
                    <span class="item-source">{source}</span>
                </div>
                <div class="item-meta">{date}</div>
                {summary_html}
            </div>"""
            items_html.append(item_html)

        return f"""
        <section class="category">
            <h2 class="category-title">{html.escape(category)}</h2>
            {''.join(items_html)}
        </section>"""

    def _generate_github_cards(self, items: List[Dict]) -> str:
        """Generate HTML for GitHub repository cards."""
        if not items:
            return """
            <div class="empty-state">
                <div class="empty-state-icon">📭</div>
                <p>No trending repositories found.</p>
            </div>"""

        cards = []
        for item in items:
            rank = item.get('rank', 0)
            name = html.escape(item.get('name', 'Unknown'))
            owner = html.escape(item.get('owner', 'Unknown'))
            stars = item.get('stars', 0)
            stars_growth = item.get('stars_growth', 0)
            description = html.escape(item.get('description', '') or '')
            topics = item.get('topics', [])
            url = html.escape(item.get('url', ''))

            # Format star count
            stars_formatted = self._format_number(stars)
            growth_formatted = self._format_number(stars_growth)

            # Rank badge class
            rank_class = f"rank-{rank}" if rank <= 3 else ""

            # Topics HTML
            topics_html = ''
            if topics:
                topic_links = []
                for topic in topics[:5]:  # Limit to 5 topics
                    topic_escaped = html.escape(str(topic))
                    topic_links.append(
                        f'<span class="topic-tag">{topic_escaped}</span>'
                    )
                topics_html = f'<div class="repo-topics">{"".join(topic_links)}</div>'

            card = f"""
            <article class="repo-card">
                <div class="card-header">
                    <span class="rank-badge {rank_class}">{rank}</span>
                    <div class="repo-info">
                        <a href="{url}" target="_blank" class="repo-name">{owner}/{name}</a>
                    </div>
                </div>
                <div class="stars-section">
                    <span class="stars-total">
                        <span class="star-icon">★</span>
                        {stars_formatted}
                    </span>
                    <span class="stars-growth">
                        <span class="growth-icon">▲</span>
                        +{growth_formatted} today
                    </span>
                </div>
                <p class="repo-description">{description}</p>
                {topics_html}
            </article>"""
            cards.append(card)

        return f'<div class="cards-grid">{"".join(cards)}</div>'

    def _format_number(self, num: int) -> str:
        """Format large numbers with K/M suffixes."""
        if num >= 1_000_000:
            return f"{num / 1_000_000:.1f}M"
        elif num >= 1_000:
            return f"{num / 1_000:.1f}K"
        return str(num)

    def save(self, content: str, filepath: str):
        """Save HTML report to file."""
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
