"""HTML report generator for RSS content - Modern Dark Theme Version."""

from datetime import datetime
from typing import List, Dict
import html


class HTMLReportGenerator:
    """Generate HTML reports from RSS feeds."""

    def __init__(self, title: str = "RSS Report"):
        self.title = title

    def generate_github_trending_html(
        self,
        title: str,
        subtitle: str,
        items: List[Dict],
        theme: str = "dark"
    ) -> str:
        """
        Generate a stunning dark-themed HTML report for GitHub trending repositories.
        Inspired by modern dev tools design with glassmorphism effects.
        """
        css = self._get_github_css()

        # Generate cards HTML
        cards_html = self._generate_github_cards(items)

        html_content = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(title)}</title>
    <style>{css}</style>
</head>
<body>
    <div class="page-background"></div>
    <div class="noise-overlay"></div>
    <div class="container">
        <header class="report-header">
            <div class="header-badge">🔥 GitHub Trending</div>
            <h1 class="main-title">{html.escape(title)}</h1>
            <p class="subtitle">{html.escape(subtitle)}</p>
            <div class="meta-info">
                <span class="meta-item">📅 {datetime.now().strftime('%Y年%m月%d日')}</span>
                <span class="meta-item">📊 共 {len(items)} 个项目</span>
            </div>
        </header>
        <main class="cards-grid">
            {cards_html}
        </main>
        <footer class="report-footer">
            <p>Generated by RSS Manager</p>
        </footer>
    </div>
</body>
</html>"""
        return html_content

    def _get_github_css(self) -> str:
        """Get stunning dark theme CSS with knowledge card design."""
        return """
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');

        :root {
            --bg-primary: #0f0f1a;
            --bg-secondary: #16162a;
            --bg-card: rgba(30, 30, 56, 0.6);
            --bg-card-hover: rgba(40, 40, 72, 0.8);
            --border-color: rgba(255, 255, 255, 0.08);
            --border-hover: rgba(255, 255, 255, 0.15);
            --text-primary: #f8fafc;
            --text-secondary: #94a3b8;
            --text-muted: #64748b;
            --accent-gold: #fbbf24;
            --accent-silver: #e2e8f0;
            --accent-bronze: #f97316;
            --accent-blue: #3b82f6;
            --accent-green: #22c55e;
            --accent-purple: #8b5cf6;
            --accent-pink: #ec4899;
            --accent-cyan: #06b6d4;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            min-height: 100vh;
            line-height: 1.6;
            position: relative;
        }

        /* Animated mesh gradient background */
        .page-background {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            pointer-events: none;
            z-index: 0;
            overflow: hidden;
            background:
                radial-gradient(ellipse at 20% 20%, rgba(139, 92, 246, 0.15) 0%, transparent 50%),
                radial-gradient(ellipse at 80% 80%, rgba(59, 130, 246, 0.15) 0%, transparent 50%),
                radial-gradient(ellipse at 50% 50%, rgba(236, 72, 153, 0.08) 0%, transparent 60%);
        }

        .noise-overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            pointer-events: none;
            z-index: 1;
            opacity: 0.03;
            background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E");
        }

        .container {
            max-width: 1400px;
            margin: 0 auto;
            padding: 48px 24px;
            position: relative;
            z-index: 2;
        }

        /* Header Styles */
        .report-header {
            text-align: center;
            padding: 64px 20px;
            margin-bottom: 48px;
            position: relative;
        }

        .header-badge {
            display: inline-flex;
            align-items: center;
            gap: 8px;
            padding: 10px 24px;
            background: linear-gradient(135deg, rgba(139, 92, 246, 0.2), rgba(59, 130, 246, 0.2));
            border: 1px solid rgba(139, 92, 246, 0.3);
            border-radius: 100px;
            font-size: 13px;
            font-weight: 600;
            color: #a78bfa;
            margin-bottom: 24px;
            letter-spacing: 0.5px;
            text-transform: uppercase;
        }

        .main-title {
            font-size: clamp(2.5rem, 5vw, 4rem);
            font-weight: 800;
            background: linear-gradient(135deg, #fff 0%, #94a3b8 50%, #64748b 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
            margin-bottom: 16px;
            letter-spacing: -0.03em;
            line-height: 1.1;
        }

        .subtitle {
            font-size: 1.25rem;
            color: var(--text-secondary);
            margin-bottom: 28px;
            font-weight: 400;
            max-width: 600px;
            margin-left: auto;
            margin-right: auto;
        }

        .meta-info {
            display: flex;
            justify-content: center;
            gap: 32px;
            flex-wrap: wrap;
        }

        .meta-item {
            font-size: 14px;
            color: var(--text-muted);
            display: flex;
            align-items: center;
            gap: 8px;
            padding: 8px 16px;
            background: rgba(255, 255, 255, 0.03);
            border-radius: 100px;
            border: 1px solid var(--border-color);
        }

        /* Cards Grid */
        .cards-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
            margin-bottom: 64px;
        }

        @media (max-width: 968px) {
            .cards-grid {
                grid-template-columns: 1fr;
            }
        }

        /* Knowledge Card */
        .knowledge-card {
            background: var(--bg-card);
            border: 1px solid var(--border-color);
            border-radius: 20px;
            padding: 24px;
            position: relative;
            overflow: hidden;
            transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);
            backdrop-filter: blur(20px);
            display: flex;
            flex-direction: column;
            gap: 16px;
        }

        .knowledge-card::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 1px;
            background: linear-gradient(90deg, transparent, rgba(255,255,255,0.15), transparent);
        }

        .knowledge-card::after {
            content: '';
            position: absolute;
            top: -50%;
            left: -50%;
            width: 200%;
            height: 200%;
            background: radial-gradient(circle, rgba(255,255,255,0.03) 0%, transparent 60%);
            opacity: 0;
            transition: opacity 0.4s;
            pointer-events: none;
        }

        .knowledge-card:hover {
            transform: translateY(-4px) scale(1.01);
            background: var(--bg-card-hover);
            border-color: var(--border-hover);
            box-shadow:
                0 20px 40px rgba(0, 0, 0, 0.4),
                0 0 0 1px rgba(255, 255, 255, 0.05),
                0 0 60px rgba(139, 92, 246, 0.1);
        }

        .knowledge-card:hover::after {
            opacity: 1;
        }

        /* Rank styles with glow */
        .knowledge-card.rank-1 {
            border-color: rgba(251, 191, 36, 0.3);
            box-shadow: 0 0 40px rgba(251, 191, 36, 0.1);
        }

        .knowledge-card.rank-2 {
            border-color: rgba(226, 232, 240, 0.2);
            box-shadow: 0 0 40px rgba(226, 232, 240, 0.08);
        }

        .knowledge-card.rank-3 {
            border-color: rgba(249, 115, 22, 0.25);
            box-shadow: 0 0 40px rgba(249, 115, 22, 0.08);
        }

        /* Card Header */
        .card-header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 16px;
        }

        .rank-section {
            display: flex;
            align-items: center;
            gap: 12px;
        }

        .rank-badge {
            width: 40px;
            height: 40px;
            border-radius: 12px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: 800;
            font-size: 16px;
            flex-shrink: 0;
        }

        .rank-badge.gold {
            background: linear-gradient(135deg, #fbbf24, #f59e0b);
            color: #000;
            box-shadow: 0 4px 20px rgba(251, 191, 36, 0.4);
        }

        .rank-badge.silver {
            background: linear-gradient(135deg, #e2e8f0, #94a3b8);
            color: #1e293b;
            box-shadow: 0 4px 20px rgba(226, 232, 240, 0.3);
        }

        .rank-badge.bronze {
            background: linear-gradient(135deg, #f97316, #ea580c);
            color: #fff;
            box-shadow: 0 4px 20px rgba(249, 115, 22, 0.3);
        }

        .rank-badge.default {
            background: linear-gradient(135deg, rgba(255,255,255,0.1), rgba(255,255,255,0.05));
            color: var(--text-secondary);
            border: 1px solid var(--border-color);
        }

        .star-section {
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .star-count {
            font-weight: 700;
            font-size: 14px;
            color: var(--accent-gold);
            display: flex;
            align-items: center;
            gap: 4px;
            padding: 6px 12px;
            background: rgba(251, 191, 36, 0.1);
            border-radius: 100px;
            border: 1px solid rgba(251, 191, 36, 0.2);
        }

        .star-growth {
            font-size: 12px;
            font-weight: 600;
            color: var(--accent-green);
            background: rgba(34, 197, 94, 0.15);
            padding: 4px 10px;
            border-radius: 100px;
            border: 1px solid rgba(34, 197, 94, 0.25);
        }

        /* Repo Name */
        .repo-name {
            font-size: 20px;
            font-weight: 700;
            line-height: 1.3;
        }

        .repo-name a {
            color: var(--text-primary);
            text-decoration: none;
            transition: all 0.2s;
            display: flex;
            align-items: center;
            gap: 6px;
            flex-wrap: wrap;
        }

        .repo-name a:hover {
            color: var(--accent-blue);
        }

        .repo-owner {
            color: var(--text-muted);
            font-weight: 500;
        }

        .repo-slash {
            color: var(--text-muted);
            opacity: 0.5;
        }

        .repo-repo {
            color: var(--text-primary);
            font-weight: 700;
        }

        .repo-name a:hover .repo-repo {
            color: var(--accent-blue);
        }

        /* Description */
        .repo-description {
            font-size: 14px;
            color: var(--text-secondary);
            line-height: 1.7;
            display: -webkit-box;
            -webkit-line-clamp: 2;
            -webkit-box-orient: vertical;
            overflow: hidden;
            flex-grow: 1;
        }

        /* Card Footer */
        .card-footer {
            display: flex;
            align-items: center;
            justify-content: space-between;
            flex-wrap: wrap;
            gap: 12px;
            padding-top: 16px;
            border-top: 1px solid var(--border-color);
        }

        .language-tag {
            display: flex;
            align-items: center;
            gap: 8px;
            font-size: 13px;
            color: var(--text-secondary);
            font-weight: 500;
        }

        .language-dot {
            width: 10px;
            height: 10px;
            border-radius: 50%;
            box-shadow: 0 0 8px currentColor;
        }

        .topics {
            display: flex;
            gap: 6px;
            flex-wrap: wrap;
        }

        .topic-tag {
            font-size: 11px;
            padding: 5px 12px;
            background: linear-gradient(135deg, rgba(59, 130, 246, 0.15), rgba(139, 92, 246, 0.15));
            color: #a78bfa;
            border-radius: 100px;
            font-weight: 600;
            border: 1px solid rgba(139, 92, 246, 0.25);
            transition: all 0.2s;
        }

        .topic-tag:hover {
            background: linear-gradient(135deg, rgba(59, 130, 246, 0.25), rgba(139, 92, 246, 0.25));
            transform: translateY(-1px);
        }

        /* Footer */
        .report-footer {
            text-align: center;
            padding: 48px;
            color: var(--text-muted);
            font-size: 14px;
            border-top: 1px solid var(--border-color);
            margin-top: 64px;
        }
        """

    def _generate_github_cards(self, items: List[Dict]) -> str:
        """Generate HTML for GitHub repository knowledge cards."""
        cards = []
        for i, item in enumerate(items, 1):
            rank_class = ""
            badge_class = "default"
            if i == 1:
                rank_class = "rank-1"
                badge_class = "gold"
            elif i == 2:
                rank_class = "rank-2"
                badge_class = "silver"
            elif i == 3:
                rank_class = "rank-3"
                badge_class = "bronze"

            owner = html.escape(item.get('owner', 'Unknown'))
            repo = html.escape(item.get('repo', 'Unknown'))
            url = html.escape(item.get('url', '#'))
            description = html.escape(item.get('description', 'No description'))
            stars = item.get('stars_formatted', str(item.get('stars', 'N/A')))
            stars_growth = item.get('stars_growth', '')
            language = html.escape(item.get('language', 'Unknown'))
            language_color = item.get('language_color', '#8b949e')
            topics = item.get('topics', [])[:3]

            growth_html = f'<span class="star-growth">+{stars_growth}</span>' if stars_growth else ''
            topics_html = ''.join([f'<span class="topic-tag">{html.escape(t)}</span>' for t in topics]) if topics else ''

            card = f"""
            <article class="knowledge-card {rank_class}">
                <div class="card-header">
                    <div class="rank-section">
                        <div class="rank-badge {badge_class}">#{i}</div>
                    </div>
                    <div class="star-section">
                        <span class="star-count">⭐ {stars}</span>
                        {growth_html}
                    </div>
                </div>
                <h3 class="repo-name">
                    <a href="{url}" target="_blank" rel="noopener">
                        <span class="repo-owner">{owner}</span>
                        <span class="repo-slash">/</span>
                        <span class="repo-repo">{repo}</span>
                    </a>
                </h3>
                <p class="repo-description">{description}</p>
                <div class="card-footer">
                    <div class="language-tag">
                        <span class="language-dot" style="background-color: {language_color}; box-shadow: 0 0 8px {language_color}"></span>
                        <span>{language}</span>
                    </div>
                    <div class="topics">{topics_html}</div>
                </div>
            </article>
            """
            cards.append(card)

        return '\n'.join(cards)

    def save(self, content: str, filepath: str):
        """Save HTML report to file."""
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)